namespace NiaBukkit.API.Util
{
    public enum Material
    {
        [MaterialAttribute(9648, 0, 0)]
        Air,
        [MaterialAttribute(22948,1)]
        Stone,
        [MaterialAttribute(21091,1, 1)]
        Granite,
        [MaterialAttribute(5477,1, 2)]
        PolishedGranite,
        [MaterialAttribute(24688,1, 3)]
        Diorite,
        [MaterialAttribute(31615,1, 4)]
        PolishedDiorite,
        [MaterialAttribute(25975,1, 5)]
        Andesite,
        [MaterialAttribute(8335,1, 6)]
        PolishedAndesite,
        [MaterialAttribute(28346,2)]
        GrassBlock,
        [MaterialAttribute(10580,3)]
        Dirt,
        [MaterialAttribute(15411,3, 1)]
        CoarseDirt,
        [MaterialAttribute(24068,3, 2)]
        Podzol,
        [MaterialAttribute(18139)]
        CrimsonNylium,
        [MaterialAttribute(26396)]
        WarpedNylium,
        [MaterialAttribute(32147,4)]
        Cobblestone,
        [MaterialAttribute(14905,5)]
        OakPlanks,
        [MaterialAttribute(14593,5, 1)]
        SprucePlanks,
        [MaterialAttribute(29322,5, 2)]
        BirchPlanks,
        [MaterialAttribute(26445,5, 3)]
        JunglePlanks,
        [MaterialAttribute(31312,5, 4)]
        AcaciaPlanks,
        [MaterialAttribute(20869,5, 5)]
        DarkOakPlanks,
        [MaterialAttribute(18812, 5)]
        CrimsonPlanks,
        [MaterialAttribute(16045,5)]
        WarpedPlanks,
        [MaterialAttribute(9636,6)]
        OakSapling,
        [MaterialAttribute(19874,6, 1)]
        SpruceSapling,
        [MaterialAttribute(31533,6, 2)]
        BirchSapling,
        [MaterialAttribute(17951,6, 3)]
        JungleSapling,
        [MaterialAttribute(20806,6, 4)]
        AcaciaSapling,
        [MaterialAttribute(14933,6, 5)]
        DarkOakSapling,
        [MaterialAttribute(23130,7)]
        Bedrock,
        
        //TODO: old Id
        [MaterialAttribute(11542,1, 2)]
        Sand,
        [MaterialAttribute(16279,1, 2)]
        RedSand,
        [MaterialAttribute(7804,1, 2)]
        Gravel,
        [MaterialAttribute(32625,1, 2)]
        GoldOre,
        [MaterialAttribute(19834,1, 2)]
        IronOre,
        [MaterialAttribute(30965,1, 2)]
        CoalOre,
        [MaterialAttribute(4185,1, 2)]
        NetherGoldOre,
        [MaterialAttribute(26723,1, 2)]
        OakLog,
        [MaterialAttribute(9726,1, 2)]
        SpruceLog,
        [MaterialAttribute(26727,1, 2)]
        BirchLog,
        [MaterialAttribute(20721,1, 2)]
        JungleLog,
        [MaterialAttribute(8385,1, 2)]
        AcaciaLog,
        [MaterialAttribute(14831,1)]
        DarkOakLog,
        [MaterialAttribute(27920,1)]
        CrimsonStem,
        [MaterialAttribute(28920,1)]
        WarpedStem,
        [MaterialAttribute(20523,1)]
        StrippedOakLog,
        [MaterialAttribute(6140,1)]
        StrippedSpruceLog,
        [MaterialAttribute(8838,1)]
        StrippedBirchLog,
        [MaterialAttribute(15476,1)]
        StrippedJungleLog,
        [MaterialAttribute(18167,1)]
        StrippedAcaciaLog,
        [MaterialAttribute(6492,1)]
        StrippedDarkOakLog,
        [MaterialAttribute(16882,1)]
        StrippedCrimsonStem,
        [MaterialAttribute(15627,1)]
        StrippedWarpedStem,
        [MaterialAttribute(31455,1)]
        StrippedOakWood,
        [MaterialAttribute(6467,1)]
        StrippedSpruceWood,
        [MaterialAttribute(22350,1)]
        StrippedBirchWood,
        [MaterialAttribute(30315,1)]
        StrippedJungleWood,
        [MaterialAttribute(27193,1)]
        StrippedAcaciaWood,
        [MaterialAttribute(16000,1)]
        StrippedDarkOakWood,
        [MaterialAttribute(27488,1)]
        StrippedCrimsonHyphae,
        [MaterialAttribute(7422,1)]
        StrippedWarpedHyphae,
        [MaterialAttribute(7378,1)]
        OakWood,
        [MaterialAttribute(32328,1)]
        SpruceWood,
        [MaterialAttribute(20913,1)]
        BirchWood,
        [MaterialAttribute(10341,1)]
        JungleWood,
        [MaterialAttribute(9541,1)]
        AcaciaWood,
        [MaterialAttribute(16995,1)]
        DarkOakWood,
        [MaterialAttribute(6550,1)]
        CrimsonHyphae,
        [MaterialAttribute(18439,1)]
        WarpedHyphae,
        [MaterialAttribute(4385,1)]
        OakLeaves,
        [MaterialAttribute(20039,1)]
        SpruceLeaves,
        [MaterialAttribute(12601,1)]
        BirchLeaves,
        [MaterialAttribute(5133,1)]
        JungleLeaves,
        [MaterialAttribute(16606,1)]
        AcaciaLeaves,
        [MaterialAttribute(22254,1)]
        DarkOakLeaves,
        [MaterialAttribute(15860,1)]
        Sponge,
        [MaterialAttribute(9043,1)]
        WetSponge,
        [MaterialAttribute(6195,1)]
        Glass,
        [MaterialAttribute(22934,1)]
        LapisOre,
        [MaterialAttribute(14485,1)]
        LapisBlock,
        [MaterialAttribute(20871,1)]
        Dispenser,
        [MaterialAttribute(13141,1)]
        Sandstone,
        [MaterialAttribute(31763,1)]
        ChiseledSandstone,
        [MaterialAttribute(6118,1)]
        CutSandStone,
        [MaterialAttribute(20979,1)]
        NNoteBlock,
        [MaterialAttribute(11064,1)]
        PoweredRail,
        [MaterialAttribute(13475,1)]
        DetectorRail,
        [MaterialAttribute(18127,1)]
        StickyPiston,
        [MaterialAttribute(9469,1)]
        Cobweb,
        [MaterialAttribute(6155,1)]
        Grass,
        [MaterialAttribute(15794,1)]
        Fern,
        [MaterialAttribute(22888,1)]
        DeadBush,
        [MaterialAttribute(23942,1)]
        Seagrass,
        [MaterialAttribute(19562,1)]
        SeaPickle,
        [MaterialAttribute(21130,1)]
        Piston,
        [MaterialAttribute(8624,1)]
        WhiteWool,
        [MaterialAttribute(23957,1)]
        OrangeWool,
        [MaterialAttribute(11853,1)]
        MagentaWool,
        [MaterialAttribute(21073,1)]
        LightBlueWool,
        [MaterialAttribute(29507,1)]
        YellowWool,
        [MaterialAttribute(10443,1)]
        LimeWool,
        [MaterialAttribute(7611,1)]
        PinkWool,
        [MaterialAttribute(27209,1)]
        GrayWool,
        [MaterialAttribute(22936,1)]
        LightGrayWool,
        [MaterialAttribute(12221,1)]
        CyanWool,
        [MaterialAttribute(11922,1)]
        PurpleWool,
        [MaterialAttribute(15738,1)]
        BlueWool,
        [MaterialAttribute(32638,1)]
        BrownWool,
        [MaterialAttribute(25085,1)]
        GreenWool,
        [MaterialAttribute(11621,1)]
        RedWool,
        [MaterialAttribute(16693,1)]
        BlackWool,
        [MaterialAttribute(30558,1)]
        Dandelion,
        [MaterialAttribute(12851,1)]
        Poppy,
        [MaterialAttribute(13432,1)]
        BlueOrchid,
        [MaterialAttribute(6871,1)]
        Allium,
        [MaterialAttribute(17608,1)]
        AzureBluet,
        [MaterialAttribute(16781,1)]
        RedTulip,
        [MaterialAttribute(26038,1)]
        OrangeTulip,
        [MaterialAttribute(31495,1)]
        WhiteTulip,
        [MaterialAttribute(27319,1)]
        PinkTulip,
        [MaterialAttribute(11709,1)]
        OxeyeDaisy,
        [MaterialAttribute(15405,1)]
        Cornflower,
        [MaterialAttribute(7185,1)]
        LilyOfTheValley,
        [MaterialAttribute(8619,1)]
        WhiteRose,
        [MaterialAttribute(9665,1)]
        BrownMushroom,
        [MaterialAttribute(19728,1)]
        RedMushRoom,
        [MaterialAttribute(26268,1)]
        CrimsonFungus,
        [MaterialAttribute(19799,1)]
        WarpedFungus,
        [MaterialAttribute(14064,1)]
        CrimsonRoots,
        [MaterialAttribute(13932,1)]
        WarpedRoots,
        [MaterialAttribute(10431,1)]
        NetherSprouts,
        [MaterialAttribute(29267,1)]
        WeepingVines,
        [MaterialAttribute(27283,1)]
        TwistingVines,
        [MaterialAttribute(7726,1)]
        SugarCane,
        [MaterialAttribute(21916,1)]
        Kelp,
        [MaterialAttribute(18728,1)]
        Bamboo,
        [MaterialAttribute(27392,1)]
        GoldBlock,
        [MaterialAttribute(24754,1)]
        IronBlock,
        [MaterialAttribute(12002,1)]
        OakSlab,
        [MaterialAttribute(28798,1)]
        SpruceSlab,
        [MaterialAttribute(13807,1)]
        BirchSlab,
        [MaterialAttribute(19117,1)]
        JungleSlab,
        [MaterialAttribute(23730,1)]
        AcaciaSlab,
        [MaterialAttribute(28852,1)]
        DarkOakSlab,
        [MaterialAttribute(4691,1)]
        CrimsonSlab,
        [MaterialAttribute(27150,1)]
        WarpedSlab,
        [MaterialAttribute(19838,1)]
        StoneSlab,
        [MaterialAttribute(24129,1)]
        SmoothStoneSlab,
        [MaterialAttribute(29830,1)]
        SandstoneSlab,
        [MaterialAttribute(30944,1)]
        CutSandstoneSlab,
        [MaterialAttribute(18658,1)]
        PetrifiedOakSlab,
        [MaterialAttribute(6340,1)]
        CobblestoneSlab,
        [MaterialAttribute(26333,1)]
        BrickSlab,
        [MaterialAttribute(19676,1)]
        StoneBrickSlab,
        [MaterialAttribute(26586,1)]
        NetherBrickSlab,
        [MaterialAttribute(4423,1)]
        QuartzSlab,
        [MaterialAttribute(17550,1)]
        RedSandstoneSlab,
        [MaterialAttribute(7220,1)]
        CutRedSandstoneSlab,
        [MaterialAttribute(11487,1)]
        PurpurSlab,
        [MaterialAttribute(31323,1)]
        PrismarineSlab,
        [MaterialAttribute(25624,1)]
        PrismarineBrickSlab,
        [MaterialAttribute(7577,1)]
        DarkPrismarineSlab,
        [MaterialAttribute(14415,1)]
        SmoothQuartz,
        [MaterialAttribute(25180,1)]
        SmoothRedSandstone,
        [MaterialAttribute(30039,1)]
        SmoothSandstone,
        [MaterialAttribute(21910,1)]
        SmoothStone,
        [MaterialAttribute(14165,1)]
        Bricks,
        [MaterialAttribute(7896,1)]
        Tnt,
        [MaterialAttribute(10069,1)]
        Bookshelf,
        [MaterialAttribute(21900,1)]
        MossyCobblestone,
        [MaterialAttribute(32723,1)]
        Obsidian,
        [MaterialAttribute(6063,1)]
        Torch,
        [MaterialAttribute(24832,1)]
        EndRod,
        [MaterialAttribute(28243,1)]
        ChorusPlant,
        [MaterialAttribute(28542,1)]
        ChorusFlower,
        [MaterialAttribute(7538,1)]
        PurpurBlock,
        [MaterialAttribute(26718,1)]
        PurpurPillar,
        [MaterialAttribute(8921,1)]
        PurpurStairs,
        [MaterialAttribute(7018,1)]
        Spawner,
        [MaterialAttribute(5449,1)]
        OakStairs,
        [MaterialAttribute(22969,1)]
        Chest,
        [MaterialAttribute(9292,1)]
        DiamondOre,
        [MaterialAttribute(5944,1)]
        DiamondBlock,
        [MaterialAttribute(20706,1)]
        CraftingTable,
        [MaterialAttribute(31166,1)]
        Farmland,
        [MaterialAttribute(8133,1)]
        Furnace,
        [MaterialAttribute(23599,1)]
        Ladder,
        [MaterialAttribute(13285,1)]
        Rail,
        [MaterialAttribute(24715,1)]
        CobblestoneStairs,
        [MaterialAttribute(15319,1)]
        Lever,
        [MaterialAttribute(22591,1)]
        StonePressurePlate,
        [MaterialAttribute(20108,1)]
        OakPressurePlate,
        [MaterialAttribute(15932,1)]
        SprucePressurePlate,
        [MaterialAttribute(9664,1)]
        BirchPressurePlate,
        [MaterialAttribute(11376,1)]
        JunglePressurePlate,
        [MaterialAttribute(17586,1)]
        AcaciaPressurePlate,
        [MaterialAttribute(31375,1)]
        DarkOakPressurePlate,
        [MaterialAttribute(18316,1)]
        CrimsonPressurePlate,
        [MaterialAttribute(29516,1)]
        WarpedPressurePlate,
        [MaterialAttribute(32340,1)]
        PolishedBlackstonePressurePlate,
        [MaterialAttribute(10887,1)]
        RedstoneOre,
        [MaterialAttribute(22547,1)]
        RedstoneTorch,
        [MaterialAttribute(14146,1)]
        Snow,
        [MaterialAttribute(30428,1)]
        Ice,
        [MaterialAttribute(19913,1)]
        SnowBlock,
        [MaterialAttribute(12191,1)]
        Cactus,
        [MaterialAttribute(27880,1)]
        Clay,
        [MaterialAttribute(19264,1)]
        Jukebox,
        [MaterialAttribute(6442,1)]
        OakFence,
        [MaterialAttribute(25416,1)]
        SpruceFence,
        [MaterialAttribute(17347,1)]
        BirchFence,
        [MaterialAttribute(14358,1)]
        JungleFence,
        [MaterialAttribute(4569,1)]
        AcaciaFence,
        [MaterialAttribute(21767,1)]
        DarkOakFence,
        [MaterialAttribute(21075,1)]
        CrimsonFence,
        [MaterialAttribute(18438,1)]
        WarpedFence,
        [MaterialAttribute(19170,1)]
        Pumpkin,
        [MaterialAttribute(25833,1)]
        CarvedPumpkin,
        [MaterialAttribute(23425,1)]
        NetherRack,
        [MaterialAttribute(16841,1)]
        SoulSand,
        [MaterialAttribute(31140,1)]
        SoulSoil,
        [MaterialAttribute(28478,1)]
        Basalt,
        [MaterialAttribute(11659,1)]
        PolishedBasalt,
        [MaterialAttribute(14292,1)]
        SoulTorch,
        [MaterialAttribute(32713,1)]
        Glowstone,
        [MaterialAttribute(13758,1)]
        JackOLantern,
        [MaterialAttribute(16927,1)]
        OakTrapdoor,
        [MaterialAttribute(10289,1)]
        SpruceTrapdoor,
        [MaterialAttribute(32585,1)]
        BirchTrapdoor,
        [MaterialAttribute(8626,1)]
        JungleTrapdoor,
        [MaterialAttribute(18343,1)]
        AcaciaTrapdoor,
        [MaterialAttribute(10355,1)]
        DarkOakTrapdoor,
        [MaterialAttribute(25056,1)]
        CrimsonTrapdoor,
        [MaterialAttribute(7708,1)]
        WarpedTrapdoor,
        [MaterialAttribute(18440,1)]
        InfestedStone,
        [MaterialAttribute(4348,1)]
        InfestedCobblestone,
        [MaterialAttribute(19749,1)]
        InfestedStoneBricks,
        [MaterialAttribute(9850,1)]
        InfestedMossyStoneBricks,
        [MaterialAttribute(7476,1)]
        InfestedCrackedStoneBricks,
        [MaterialAttribute(4728,1)]
        InfestedChiseledStoneBricks,
        [MaterialAttribute(6962,1)]
        StoneBricks,
        [MaterialAttribute(16415,1)]
        MossyStoneBricks,
        [MaterialAttribute(27869,1)]
        CrackedStoneBricks,
        [MaterialAttribute(9087,1)]
        ChiseledStoneBricks,
        [MaterialAttribute(6291,1)]
        BrownMushroomBlock,
        [MaterialAttribute(20766,1)]
        RedMushroomBlock,
        [MaterialAttribute(16543,1)]
        MushroomStem,
        [MaterialAttribute(9378,1)]
        IronBars,
        [MaterialAttribute(28265,1)]
        Chain,
        [MaterialAttribute(5709,1)]
        GlassPane,
        [MaterialAttribute(25172,1)]
        Melon,
        [MaterialAttribute(14564,1)]
        Vine,
        [MaterialAttribute(16689,1)]
        OakFenceGate,
        [MaterialAttribute(26423,1)]
        SpruceFenceGate,
        [MaterialAttribute(6322,1)]
        BirchFenceGate,
        [MaterialAttribute(21360,1)]
        JungleFenceGate,
        [MaterialAttribute(14145,1)]
        AcaciaFenceGate,
        [MaterialAttribute(10679,1)]
        DarkOakFenceGate,
        [MaterialAttribute(15602,1)]
        CrimsonFenceGate,
        [MaterialAttribute(11115,1)]
        WarpedFenceGate,
        [MaterialAttribute(21534,1)]
        BrickStairs,
        [MaterialAttribute(27032,1)]
        StoneBrickStairs,
        [MaterialAttribute(9913,1)]
        Mycelium,
        [MaterialAttribute(19271,1)]
        LilyPad,
        [MaterialAttribute(27802,1)]
        NetherBricks,
        [MaterialAttribute(10888,1)]
        CrackedNetherBricks,
        [MaterialAttribute(21613,1)]
        ChiseledNetherBricks,
        [MaterialAttribute(5286,1)]
        NetherBrickFence,
        [MaterialAttribute(12085,1)]
        NetherBrickStairs,
        [MaterialAttribute(16255,1)]
        EnchantingTable,
        [MaterialAttribute(15480,1)]
        EndPortalFrame,
        [MaterialAttribute(29686,1)]
        EndStone,
        [MaterialAttribute(20314,1)]
        EndStoneBricks,
        [MaterialAttribute(29946,1)]
        DragonEgg,
        [MaterialAttribute(8217,1)]
        RedstoneLamp,
        [MaterialAttribute(18474,1)]
        SandstoneStairs,
        [MaterialAttribute(16630,1)]
        EmeraldOre,
        [MaterialAttribute(32349,1)]
        EnderChest,
        [MaterialAttribute(8130,1)]
        TripwireHook,
        [MaterialAttribute(9914,1)]
        EmeraldBlock,
        [MaterialAttribute(11192,1)]
        SpruceStairs,
        [MaterialAttribute(7657,1)]
        BirchStairs,
        [MaterialAttribute(20636,1)]
        JungleStairs,
        [MaterialAttribute(32442,1)]
        CrimsonStairs,
        [MaterialAttribute(17721,1)]
        WarpedStairs,
        [MaterialAttribute(4355,1)]
        CommandBlock,
        [MaterialAttribute(6608,1)]
        Beacon,
        [MaterialAttribute(12616,1)]
        CobblestoneWall,
        [MaterialAttribute(11536,1)]
        MossyCobblestoneWall,
        [MaterialAttribute(18995,1)]
        BrickWall,
        [MaterialAttribute(18184,1)]
        PrismarineWall,
        [MaterialAttribute(4753,1)]
        RedSandstoneWall,
        [MaterialAttribute(18259,1)]
        MossyStoneBrickWall,
        [MaterialAttribute(23279,1)]
        GraniteWall,
        [MaterialAttribute(29073,1)]
        StoneBrickWall,
        [MaterialAttribute(10398,1)]
        NetherBrickWall,
        [MaterialAttribute(14938,1)]
        AndesiteWall,
        [MaterialAttribute(4580,1)]
        RedNetherBrickWall,
        [MaterialAttribute(18470,1)]
        SandstoneWall,
        [MaterialAttribute(27225,1)]
        EndStoneBrickWall,
        [MaterialAttribute(17412,1)]
        DioriteWall,
        [MaterialAttribute(17327,1)]
        BlackstoneWall,
        [MaterialAttribute(15119,1)]
        PolishedBlackstoneWall,
        [MaterialAttribute(9540,1)]
        PolishedBlackstoneBrickWall,
        [MaterialAttribute(12279,1)]
        StoneButton,
        [MaterialAttribute(13510,1)]
        OakButton,
        [MaterialAttribute(23281,1)]
        SpruceButton,
        [MaterialAttribute(26934,1)]
        BirchButton,
        [MaterialAttribute(25317,1)]
        JungleButton,
        [MaterialAttribute(13993,1)]
        AcaciaButton,
        [MaterialAttribute(6214,1)]
        DarkOakButton,
        [MaterialAttribute(26799,1)]
        CrimsonButton,
        [MaterialAttribute(25264,1)]
        WarpedButton,
        [MaterialAttribute(20760,1)]
        PolishedBlackstoneButton,
        [MaterialAttribute(18718,1)]
        Anvil,
        [MaterialAttribute(10623,1)]
        ChippedAnvil,
        [MaterialAttribute(10274,1)]
        DamagedAnvil,
        [MaterialAttribute(18970,1)]
        TrappedChest,
        [MaterialAttribute(14875,1)]
        LightWeightedPressurePlate,
        [MaterialAttribute(16970,1)]
        HeavyWeightedPressurePlate,
        [MaterialAttribute(8864,1)]
        DaylightDetector,
        [MaterialAttribute(19496,1)]
        RedstoneBlock,
        [MaterialAttribute(4807,1)]
        NetherQuartzOre,
        [MaterialAttribute(31974,1)]
        Hopper,
        [MaterialAttribute(30964,1)]
        ChiseledQuartzBlock,
        [MaterialAttribute(11987,1)]
        QuartzBlock,
        [MaterialAttribute(23358,1)]
        QuartzBricks,
        [MaterialAttribute(16452,1)]
        QuartzPillar,
        [MaterialAttribute(24079,1)]
        QuartzStairs,
        [MaterialAttribute(5834,1)]
        ActivatorRail,
        [MaterialAttribute(31273,1)]
        Dropper,
        [MaterialAttribute(20975,1)]
        WhiteTerracotta,
        [MaterialAttribute(18684,1)]
        OrangeTerracotta,
        [MaterialAttribute(25900,1)]
        MagentaTerracotta,
        [MaterialAttribute(31779,1)]
        LightBlueTerracotta,
        [MaterialAttribute(32129,1)]
        YellowTerracotta,
        [MaterialAttribute(24013,1)]
        LimeTerracotta,
        [MaterialAttribute(23727,1)]
        PinkTerracotta,
        [MaterialAttribute(18004,1)]
        GrayTerracotta,
        [MaterialAttribute(26388,1)]
        LightGrayTerracotta,
        [MaterialAttribute(25940,1)]
        CyanTerracotta,
        [MaterialAttribute(10387,1)]
        PurpleTerracotta,
        [MaterialAttribute(5236,1)]
        BlueTerracotta,
        [MaterialAttribute(23664,1)]
        BrownTerracotta,
        [MaterialAttribute(4105,1)]
        GreenTerracotta,
        [MaterialAttribute(5086,1)]
        RedTerracotta,
        [MaterialAttribute(26691,1)]
        BlackTerracotta,
        [MaterialAttribute(26453,1)]
        Barrier,
        [MaterialAttribute(17095,1)]
        IronTrapdoor,
        [MaterialAttribute(17461,1)]
        HayBlock,
        [MaterialAttribute(15117,1)]
        WhiteCarpet,
        [MaterialAttribute(24752,1)]
        OrangeCarpet,
        [MaterialAttribute(6180,1)]
        MagentaCarpet,
        [MaterialAttribute(21194,1)]
        LightBlueCarpet,
        [MaterialAttribute(18149,1)]
        YellowCarpet,
        [MaterialAttribute(15443,1)]
        LimeCarpet,
        [MaterialAttribute(27381,1)]
        PinkCarpet,
        [MaterialAttribute(26991,1)]
        GrayCarpet,
        [MaterialAttribute(11317,1)]
        LightGrayCarpet,
        [MaterialAttribute(9742,1)]
        CyanCarpet,
        [MaterialAttribute(5574,1)]
        PurpleCarpet,
        [MaterialAttribute(13292,1)]
        BlueCarpet,
        [MaterialAttribute(23352,1)]
        BrownCarpet,
        [MaterialAttribute(7780,1)]
        GreenCarpet,
        [MaterialAttribute(5424,1)]
        RedCarpet,
        [MaterialAttribute(6056,1)]
        BlackCarpet,
        [MaterialAttribute(16544,1)]
        Terracotta,
        [MaterialAttribute(27968,1)]
        CoalBlock,
        [MaterialAttribute(28993,1)]
        PackedIce,
        [MaterialAttribute(17453,1)]
        AcaciaStairs,
        [MaterialAttribute(22921,1)]
        DarkOakStairs,
        [MaterialAttribute(31892,1)]
        SlimeBlock,
        [MaterialAttribute(8604,1)]
        GrassPath,
        [MaterialAttribute(7408,1)]
        Sunflower,
        [MaterialAttribute(22837,1)]
        Lilac,
        [MaterialAttribute(6080,1)]
        RoseBush,
        [MaterialAttribute(21155,1)]
        Peony,
        [MaterialAttribute(21559,1)]
        TallGrass,
        [MaterialAttribute(30177,1)]
        LargeFern,
        [MaterialAttribute(31190,1)]
        WhiteStainedGlass,
        [MaterialAttribute(25142,1)]
        OrangeStainedGlass,
        [MaterialAttribute(26814,1)]
        MagentaStainedGlass,
        [MaterialAttribute(17162,1)]
        LightBlueStainedGlass,
        [MaterialAttribute(12182,1)]
        YellowStainedGlass,
        [MaterialAttribute(24266,1)]
        LimeStainedGlass,
        [MaterialAttribute(16164,1)]
        PinkStainedGlass,
        [MaterialAttribute(29979,1)]
        GrayStainedGlass,
        [MaterialAttribute(5843,1)]
        LightGrayStainedGlass,
        [MaterialAttribute(30604,1)]
        CyanStainedGlass,
        [MaterialAttribute(21845,1)]
        PurpleStainedGlass,
        [MaterialAttribute(7107,1)]
        BlueStainedGlass,
        [MaterialAttribute(20945,1)]
        BrownStainedGlass,
        [MaterialAttribute(22503,1)]
        GreenStainedGlass,
        [MaterialAttribute(9717,1)]
        RedStainedGlass,
        [MaterialAttribute(13941,1)]
        BlackStainedGlass,
        [MaterialAttribute(10557,1)]
        WhiteStainedGlassPane,
        [MaterialAttribute(21089,1)]
        OrangeStainedGlassPane,
        [MaterialAttribute(14082,1)]
        MagentaStainedGlassPane,
        [MaterialAttribute(18721,1)]
        LightBlueStainedGlassPane,
        [MaterialAttribute(20298,1)]
        YellowStainedGlassPane,
        [MaterialAttribute(10610,1)]
        LimeStainedGlassPane,
        [MaterialAttribute(24637,1)]
        PinkStainedGlassPane,
        [MaterialAttribute(25272,1)]
        GrayStainedGlassPane,
        [MaterialAttribute(19008,1)]
        LightGrayStainedGlassPane,
        [MaterialAttribute(11784,1)]
        CyanStainedGlassPane,
        [MaterialAttribute(10948,1)]
        PurpleStainedGlassPane,
        [MaterialAttribute(28484,1)]
        BlueStainedGlassPane,
        [MaterialAttribute(17557,1)]
        BrownStainedGlassPane,
        [MaterialAttribute(4767,1)]
        GreenStainedGlassPane,
        [MaterialAttribute(8630,1)]
        RedStainedGlassPane,
        [MaterialAttribute(13201,1)]
        BlackStainedGlassPane,
        [MaterialAttribute(7539,1)]
        Prismarine,
        [MaterialAttribute(29118,1)]
        PrismarineBricks,
        [MaterialAttribute(19940,1)]
        DarkPrismarine,
        [MaterialAttribute(19217,1)]
        PrismarineStairs,
        [MaterialAttribute(15445,1)]
        PrismarineBrickStairs,
        [MaterialAttribute(26511,1)]
        DarkPrismarineStairs,
        [MaterialAttribute(20780,1)]
        SeaLantern,
        [MaterialAttribute(9092,1)]
        RedSandstone,
        [MaterialAttribute(15529,1)]
        ChiseledRedSandstone,
        [MaterialAttribute(26842,1)]
        CutRedSandstone,
        [MaterialAttribute(25466,1)]
        RedSandstoneStairs,
        [MaterialAttribute(12405,1)]
        RepeatingCommandBlock,
        [MaterialAttribute(26798,1)]
        ChainCommandBlock,
        [MaterialAttribute(25927,1)]
        MagmaBlock,
        [MaterialAttribute(15486,1)]
        NetherWartBlock,
        [MaterialAttribute(15463,1)]
        WarpedWartBlock,
        [MaterialAttribute(18056,1)]
        RedNetherBricks,
        [MaterialAttribute(17312,1)]
        BoneBlock,
        [MaterialAttribute(30806,1)]
        StructureVoid,
        [MaterialAttribute(10726,1)]
        Observer,
        [MaterialAttribute(7776,1)]
        ShulkerBox,
        [MaterialAttribute(31750,1)]
        WhiteShulkerBox,
        [MaterialAttribute(21673,1)]
        OrangeShulkerBox,
        [MaterialAttribute(21566,1)]
        MagentaShulkerBox,
        [MaterialAttribute(18226,1)]
        LightBlueShulkerBox,
        [MaterialAttribute(28700,1)]
        YellowShulkerBox,
        [MaterialAttribute(28360,1)]
        LimeShulkerBox,
        [MaterialAttribute(24968,1)]
        PinkShulkerBox,
        [MaterialAttribute(12754,1)]
        GrayShulkerBox,
        [MaterialAttribute(21345,1)]
        LightGrayShulkerBox,
        [MaterialAttribute(28123,1)]
        CyanShulkerBox,
        [MaterialAttribute(10373,1)]
        PurpleShulkerBox,
        [MaterialAttribute(11476,1)]
        BlueShulkerBox,
        [MaterialAttribute(24230,1)]
        BrownShulkerBox,
        [MaterialAttribute(9377,1)]
        GreenShulkerBox,
        [MaterialAttribute(32448,1)]
        RedShulkerBox,
        [MaterialAttribute(24076,1)]
        BlackShulkerBox,
        [MaterialAttribute(11326,1)]
        WhiteGlazedTerracotta,
        [MaterialAttribute(27451,1)]
        OrangeGlazedTerracotta,
        [MaterialAttribute(8067,1)]
        MagentaGlazedTerracotta,
        [MaterialAttribute(4336,1)]
        LightBlueGlazedTerracotta,
        [MaterialAttribute(10914,1)]
        YellowGlazedTerracotta,
        [MaterialAttribute(13861,1)]
        LimeGlazedTerracotta,
        [MaterialAttribute(10260,1)]
        PinkGlazedTerracotta,
        [MaterialAttribute(6256,1)]
        GrayGlazedTerracotta,
        [MaterialAttribute(10707,1)]
        LightGrayGlazedTerracotta,
        [MaterialAttribute(9550,1)]
        CyanGlazedTerracotta,
        [MaterialAttribute(4818,1)]
        PurpleGlazedTerracotta,
        [MaterialAttribute(23823,1)]
        BlueGlazedTerracotta,
        [MaterialAttribute(5655,1)]
        BrownGlazedTerracotta,
        [MaterialAttribute(6958,1)]
        GreenGlazedTerracotta,
        [MaterialAttribute(24989,1)]
        RedGlazedTerracotta,
        [MaterialAttribute(29678,1)]
        BlackGlazedTerracotta,
        [MaterialAttribute(6281,1)]
        WhiteConcrete,
        [MaterialAttribute(19914,1)]
        OrangeConcrete,
        [MaterialAttribute(20591,1)]
        MagentaConcrete,
        [MaterialAttribute(29481,1)]
        LightBlueConcrete,
        [MaterialAttribute(15722,1)]
        YellowConcrete,
        [MaterialAttribute(5863,1)]
        LimeConcrete,
        [MaterialAttribute(5227,1)]
        PinkConcrete,
        [MaterialAttribute(13959,1)]
        GrayConcrete,
        [MaterialAttribute(14453,1)]
        LightGrayConcrete,
        [MaterialAttribute(26522,1)]
        CyanConcrete,
        [MaterialAttribute(20623,1)]
        PurpleConcrete,
        [MaterialAttribute(18756,1)]
        BlueConcrete,
        [MaterialAttribute(19006,1)]
        BrownConcrete,
        [MaterialAttribute(17949,1)]
        GreenConcrete,
        [MaterialAttribute(8032,1)]
        RedConcrete,
        [MaterialAttribute(13338,1)]
        BlackConcrete,
        [MaterialAttribute(10363,1)]
        WhiteConcretePowder,
        [MaterialAttribute(30159,1)]
        OrangeConcretePowder,
        [MaterialAttribute(8272,1)]
        MagentaConcretePowder,
        [MaterialAttribute(31206,1)]
        LightBlueConcretePowder,
        [MaterialAttribute(10655,1)]
        YellowConcretePowder,
        [MaterialAttribute(28859,1)]
        LimeConcretePowder,
        [MaterialAttribute(6421,1)]
        PinkConcretePowder,
        [MaterialAttribute(13031,1)]
        GrayConcretePowder,
        [MaterialAttribute(21589,1)]
        LightGrayConcretePowder,
        [MaterialAttribute(15734,1)]
        CyanConcretePowder,
        [MaterialAttribute(26808,1)]
        PurpleConcretePowder,
        [MaterialAttribute(17773,1)]
        BlueConcretePowder,
        [MaterialAttribute(21485,1)]
        BrownConcretePowder,
        [MaterialAttribute(6904,1)]
        GreenConcretePowder,
        [MaterialAttribute(13286,1)]
        RedConcretePowder,
        [MaterialAttribute(16150,1)]
        BlackConcretePowder,
        [MaterialAttribute(32101,1)]
        TurtleEgg,
        [MaterialAttribute(28350,1)]
        DeadTubeCoralBlock,
        [MaterialAttribute(12979,1)]
        DeadBrainCoralBlock,
        [MaterialAttribute(28220,1)]
        DeadBubbleCoralBlock,
        [MaterialAttribute(5307,1)]
        DeadFireCoralBlock,
        [MaterialAttribute(15103,1)]
        DeadHornCoralBlock,
        [MaterialAttribute(23723,1)]
        TubeCoralBlock,
        [MaterialAttribute(30618,1)]
        BrainCoralBlock,
        [MaterialAttribute(15437,1)]
        BubbleCoralBlock,
        [MaterialAttribute(12119,1)]
        FireCoralBlock,
        [MaterialAttribute(19958,1)]
        HornCoralBlock,
        [MaterialAttribute(23048,1)]
        TubeCoral,
        [MaterialAttribute(31316,1)]
        BrainCoral,
        [MaterialAttribute(12464,1)]
        BubbleCoral,
        [MaterialAttribute(29151,1)]
        FireCoral,
        [MaterialAttribute(19511,1)]
        HornCoral,
        [MaterialAttribute(9116,1)]
        DeadBrainCoral,
        [MaterialAttribute(30583,1)]
        DeadBubbleCoral,
        [MaterialAttribute(8365,1)]
        DeadFireCoral,
        [MaterialAttribute(5755,1)]
        DeadHornCoral,
        [MaterialAttribute(18028,1)]
        DeadTubeCoral,
        [MaterialAttribute(19929,1)]
        TubeCoralFan,
        [MaterialAttribute(13849,1)]
        BrainCoralFan,
        [MaterialAttribute(10795,1)]
        BubbleCoralFan,
        [MaterialAttribute(11112,1)]
        FireCoralFan,
        [MaterialAttribute(13610,1)]
        HornCoralFan,
        [MaterialAttribute(17628,1)]
        DeadTubeCoralFan,
        [MaterialAttribute(26150,1)]
        DeadBrainCoralFan,
        [MaterialAttribute(17322,1)]
        DeadBubbleCoralFan,
        [MaterialAttribute(27073,1)]
        DeadFireCoralFan,
        [MaterialAttribute(11387,1)]
        DeadHornCoralFan,
        [MaterialAttribute(22449,1)]
        BlueIce,
        [MaterialAttribute(5148,1)]
        Conduit,
        [MaterialAttribute(29588,1)]
        PolishedGraniteStairs,
        [MaterialAttribute(17561,1)]
        SmoothRedSandstoneStairs,
        [MaterialAttribute(27578,1)]
        MossyStoneBrickStairs,
        [MaterialAttribute(4625,1)]
        PolishedDioriteStairs,
        [MaterialAttribute(29210,1)]
        MossyCobblestoneStairs,
        [MaterialAttribute(28831,1)]
        EndStoneBrickStairs,
        [MaterialAttribute(23784,1)]
        StoneStairs,
        [MaterialAttribute(21183,1)]
        SmoothSandstoneStairs,
        [MaterialAttribute(19560,1)]
        SmoothQuartzStairs,
        [MaterialAttribute(21840,1)]
        GraniteStairs,
        [MaterialAttribute(17747,1)]
        AndesiteStairs,
        [MaterialAttribute(26374,1)]
        RedNetherBrickStairs,
        [MaterialAttribute(7573,1)]
        PolishedAndesiteStairs,
        [MaterialAttribute(13134,1)]
        DioriteStairs,
        [MaterialAttribute(4521,1)]
        PolishedGraniteSlab,
        [MaterialAttribute(16304,1)]
        SmoothRedSandstoneSlab,
        [MaterialAttribute(14002,1)]
        MossyStoneBrickSlab,
        [MaterialAttribute(18303,1)]
        PolishedDioriteSlab,
        [MaterialAttribute(12139,1)]
        MossyCobblestoneSlab,
        [MaterialAttribute(23239,1)]
        EndStoneBrickSlab,
        [MaterialAttribute(9030,1)]
        SmoothSandstoneSlab,
        [MaterialAttribute(26543,1)]
        SmoothQuartzSlab,
        [MaterialAttribute(10901,1)]
        GraniteSlab,
        [MaterialAttribute(32124,1)]
        AndesiteSlab,
        [MaterialAttribute(12462,1)]
        RedNetherBrickSlab,
        [MaterialAttribute(24573,1)]
        PolishedAndesiteSlab,
        [MaterialAttribute(10715,1)]
        DioriteSlab,
        [MaterialAttribute(15757,1)]
        Scaffolding,
        [MaterialAttribute(4788,1)]
        IronDoor,
        [MaterialAttribute(20341,1)]
        OakDoor,
        [MaterialAttribute(10642,1)]
        SpruceDoor,
        [MaterialAttribute(14759,1)]
        BirchDoor,
        [MaterialAttribute(28163,1)]
        JungleDoor,
        [MaterialAttribute(23797,1)]
        AcaciaDoor,
        [MaterialAttribute(10669,1)]
        DarkOakDoor,
        [MaterialAttribute(19544,1)]
        CrimsonDoor,
        [MaterialAttribute(15062,1)]
        WarpedDoor,
        [MaterialAttribute(28823,1)]
        Repeater,
        [MaterialAttribute(18911,1)]
        Comparator,
        [MaterialAttribute(26831,1)]
        StructureBlock,
        [MaterialAttribute(17398,1)]
        Jigsaw,
        [MaterialAttribute(30120,1)]
        TurtleHelmet,
        [MaterialAttribute(11914,1)]
        Scute,
        [MaterialAttribute(28620,1)]
        FlintAndSteel,
        [MaterialAttribute(7720,1)]
        Apple,
        [MaterialAttribute(8745,1)]
        Bow,
        [MaterialAttribute(31091,1)]
        Arrow,
        [MaterialAttribute(29067,1)]
        Coal,
        [MaterialAttribute(5390,1)]
        Charcoal,
        [MaterialAttribute(20865,1)]
        Diamond,
        [MaterialAttribute(24895,1)]
        IronIngot,
        [MaterialAttribute(28927,1)]
        GoldIngot,
        [MaterialAttribute(32457,1)]
        NetheriteIngot,
        [MaterialAttribute(29331,1)]
        NetheriteScrap,
        [MaterialAttribute(7175,1)]
        WoodenSword,
        [MaterialAttribute(28432,1)]
        WoodenShovel,
        [MaterialAttribute(12792,1)]
        WoodenPickaxe,
        [MaterialAttribute(6292,1)]
        WoodenAxe,
        [MaterialAttribute(16043,1)]
        WoodenHoe,
        [MaterialAttribute(25084,1)]
        StoneSword,
        [MaterialAttribute(9520,1)]
        StoneShovel,
        [MaterialAttribute(14611,1)]
        StonePickaxe,
        [MaterialAttribute(6338,1)]
        StoneAxe,
        [MaterialAttribute(22855,1)]
        StoneHoe,
        [MaterialAttribute(10505,1)]
        GoldenSword,
        [MaterialAttribute(15597,1)]
        GoldenShovel,
        [MaterialAttribute(25898,1)]
        GoldenPickaxe,
        [MaterialAttribute(4878,1)]
        GoldenAxe,
        [MaterialAttribute(19337,1)]
        GoldenHoe,
        [MaterialAttribute(10904,1)]
        IronSword,
        [MaterialAttribute(30045,1)]
        IronShovel,
        [MaterialAttribute(8842,1)]
        IronPickaxe,
        [MaterialAttribute(15894,1)]
        IronAxe,
        [MaterialAttribute(11339,1)]
        IronHoe,
        [MaterialAttribute(27707,1)]
        DiamondSword,
        [MaterialAttribute(25415,1)]
        DiamondShovel,
        [MaterialAttribute(24291,1)]
        DiamondPickaxe,
        [MaterialAttribute(27277,1)]
        DiamondAxe,
        [MaterialAttribute(24050,1)]
        DiamondHoe,
        [MaterialAttribute(23871,1)]
        NetheriteSword,
        [MaterialAttribute(29728,1)]
        NetheriteShovel,
        [MaterialAttribute(9930,1)]
        NetheritePickaxe,
        [MaterialAttribute(29533,1)]
        NetheriteAxe,
        [MaterialAttribute(27385,1)]
        NetheriteHoe,
        [MaterialAttribute(9773,1)]
        Stick,
        [MaterialAttribute(32661,1)]
        Bowl,
        [MaterialAttribute(16336,1)]
        MushroomStew,
        [MaterialAttribute(12806,1)]
        String,
        [MaterialAttribute(30548,1)]
        Feather,
        [MaterialAttribute(29974,1)]
        Gunpowder,
        [MaterialAttribute(28742,1)]
        WheatSeeds,
        [MaterialAttribute(27709,1)]
        Wheat,
        [MaterialAttribute(32049,1)]
        Bread,
        [MaterialAttribute(11624,1)]
        LeatherHelmet,
        [MaterialAttribute(29275,1)]
        LeatherChestplate,
        [MaterialAttribute(28210,1)]
        LeatherLeggings,
        [MaterialAttribute(15282,1)]
        LeatherBoots,
        [MaterialAttribute(26114,1)]
        ChainmailHelmet,
        [MaterialAttribute(23602,1)]
        ChainmailChestplate,
        [MaterialAttribute(19087,1)]
        ChainmailLeggings,
        [MaterialAttribute(17953,1)]
        ChainmailBoots,
        [MaterialAttribute(12025,1)]
        IronHelmet,
        [MaterialAttribute(28112,1)]
        IronChestplate,
        [MaterialAttribute(18951,1)]
        IronLeggings,
        [MaterialAttribute(8531,1)]
        IronBoots,
        [MaterialAttribute(10755,1)]
        DiamondHelmet,
        [MaterialAttribute(32099,1)]
        DiamondChestplate,
        [MaterialAttribute(11202,1)]
        DiamondLeggings,
        [MaterialAttribute(16522,1)]
        DiamondBoots,
        [MaterialAttribute(7945,1)]
        GoldenHelmet,
        [MaterialAttribute(4507,1)]
        GoldenChestplate,
        [MaterialAttribute(21002,1)]
        GoldenLeggings,
        [MaterialAttribute(7859,1)]
        GoldenBoots,
        [MaterialAttribute(15907,1)]
        NetheriteHelmet,
        [MaterialAttribute(6106,1)]
        NetheriteChestplate,
        [MaterialAttribute(25605,1)]
        NetheriteLeggings,
        [MaterialAttribute(8923,1)]
        NetheriteBoots,
        [MaterialAttribute(23596,1)]
        Flint,
        [MaterialAttribute(30896,1)]
        Porkchop,
        [MaterialAttribute(27231,1)]
        CookedPorkchop,
        [MaterialAttribute(23945,1)]
        Painting,
        [MaterialAttribute(27732,1)]
        GoldenApple,
        [MaterialAttribute(8280,1)]
        EnchantedGoldenApple,
        [MaterialAttribute(8192,1)]
        OakSign,
        [MaterialAttribute(21502,1)]
        SpruceSign,
        [MaterialAttribute(11351,1)]
        BirchSign,
        [MaterialAttribute(24717,1)]
        JungleSign,
        [MaterialAttribute(29808,1)]
        AcaciaSign,
        [MaterialAttribute(15127,1)]
        DarkOakSign,
        [MaterialAttribute(12162,1)]
        CrimsonSign,
        [MaterialAttribute(10407,1)]
        WarpedSign,
        [MaterialAttribute(15215,1)]
        Bucket,
        [MaterialAttribute(8802,1)]
        WaterBucket,
        [MaterialAttribute(9228,1)]
        LavaBucket,
        [MaterialAttribute(14352,1)]
        Minecart,
        [MaterialAttribute(30206,1)]
        Saddle,
        [MaterialAttribute(11233,1)]
        Redstone,
        [MaterialAttribute(19487,1)]
        Snowball,
        [MaterialAttribute(17570,1)]
        OakBoat,
        [MaterialAttribute(16414,1)]
        Leather,
        [MaterialAttribute(9680,1)]
        MilkBucket,
        [MaterialAttribute(8861,1)]
        PufferfishBucket,
        [MaterialAttribute(31427,1)]
        SalmonBucket,
        [MaterialAttribute(28601,1)]
        CodBucket,
        [MaterialAttribute(29995,1)]
        TropicalFishBucket,
        [MaterialAttribute(6820,1)]
        Brick,
        [MaterialAttribute(24603,1)]
        ClayBall,
        [MaterialAttribute(12966,1)]
        DriedKelpBlock,
        [MaterialAttribute(9923,1)]
        Paper,
        [MaterialAttribute(23097,1)]
        Book,
        [MaterialAttribute(5242,1)]
        SlimeBall,
        [MaterialAttribute(4497,1)]
        ChestMinecart,
        [MaterialAttribute(14196,1)]
        FurnaceMinecart,
        [MaterialAttribute(21603,1)]
        Egg,
        [MaterialAttribute(24139,1)]
        Compass,
        [MaterialAttribute(4167,1)]
        FishingRod,
        [MaterialAttribute(14980,1)]
        Clock,
        [MaterialAttribute(6665,1)]
        GlowstoneDust,
        [MaterialAttribute(24691,1)]
        Cod,
        [MaterialAttribute(18516,1)]
        Salmon,
        [MaterialAttribute(24879,1)]
        TropicalFish,
        [MaterialAttribute(8115,1)]
        Pufferfish,
        [MaterialAttribute(9681,1)]
        CookedCod,
        [MaterialAttribute(5615,1)]
        CookedSalmon,
        [MaterialAttribute(7184,1)]
        InkSac,
        [MaterialAttribute(30186,1)]
        CocoaBeans,
        [MaterialAttribute(11075,1)]
        LapisLazuli,
        [MaterialAttribute(10758,1)]
        WhiteDye,
        [MaterialAttribute(13866,1)]
        OrangeDye,
        [MaterialAttribute(11788,1)]
        MagentaDye,
        [MaterialAttribute(28738,1)]
        LightBlueDye,
        [MaterialAttribute(5952,1)]
        YellowDye,
        [MaterialAttribute(6147,1)]
        LimeDye,
        [MaterialAttribute(31151,1)]
        PinkDye,
        [MaterialAttribute(9184,1)]
        GrayDye,
        [MaterialAttribute(27643,1)]
        LightGrayDye,
        [MaterialAttribute(8043,1)]
        CyanDye,
        [MaterialAttribute(6347,1)]
        PurpleDye,
        [MaterialAttribute(11588,1)]
        BlueDye,
        [MaterialAttribute(7648,1)]
        BrownDye,
        [MaterialAttribute(23215,1)]
        GreenDye,
        [MaterialAttribute(5728,1)]
        RedDye,
        [MaterialAttribute(6202,1)]
        BlackDye,
        [MaterialAttribute(32458,1)]
        BoneMeal,
        [MaterialAttribute(5686,1)]
        Bone,
        [MaterialAttribute(30638,1)]
        Sugar,
        [MaterialAttribute(27048,1)]
        Cake,
        [MaterialAttribute(8185,1)]
        WhiteBed,
        [MaterialAttribute(11194,1)]
        OrangeBed,
        [MaterialAttribute(20061,1)]
        MagentaBed,
        [MaterialAttribute(20957,1)]
        LightBlueBed,
        [MaterialAttribute(30410,1)]
        YellowBed,
        [MaterialAttribute(27860,1)]
        LimeBed,
        [MaterialAttribute(13795,1)]
        PinkBed,
        [MaterialAttribute(15745,1)]
        GrayBed,
        [MaterialAttribute(5090,1)]
        LightGrayBed,
        [MaterialAttribute(16746,1)]
        CyanBed,
        [MaterialAttribute(29755,1)]
        PurpleBed,
        [MaterialAttribute(12714,1)]
        BlueBed,
        [MaterialAttribute(26672,1)]
        BrownBed,
        [MaterialAttribute(13797,1)]
        GreenBed,
        [MaterialAttribute(30910,1)]
        RedBed,
        [MaterialAttribute(20490,1)]
        BlackBed,
        [MaterialAttribute(27431,1)]
        Cookie,
        [MaterialAttribute(23504,1)]
        FilledMap,
        [MaterialAttribute(27971,1)]
        Shears,
        [MaterialAttribute(5347,1)]
        MelonSlice,
        [MaterialAttribute(21042,1)]
        DriedKelp,
        [MaterialAttribute(28985,1)]
        PumpkinSeeds,
        [MaterialAttribute(18340,1)]
        MelonSeeds,
        [MaterialAttribute(4803,1)]
        Beef,
        [MaterialAttribute(21595,1)]
        CookedBeef,
        [MaterialAttribute(17281,1)]
        Chicken,
        [MaterialAttribute(16984,1)]
        CookedChicken,
        [MaterialAttribute(21591,1)]
        RottenFlesh,
        [MaterialAttribute(5259,1)]
        EnderPearl,
        [MaterialAttribute(8289,1)]
        BlazeRod,
        [MaterialAttribute(18222,1)]
        GhastTear,
        [MaterialAttribute(28814,1)]
        GoldNugget,
        [MaterialAttribute(29227,1)]
        NetherWart,
        [MaterialAttribute(24020,1)]
        Potion,
        [MaterialAttribute(6116,1)]
        GlassBottle,
        [MaterialAttribute(9318,1)]
        SpiderEye,
        [MaterialAttribute(19386,1)]
        FermentedSpiderEye,
        [MaterialAttribute(18941,1)]
        BlazePowder,
        [MaterialAttribute(25097,1)]
        MagmaCream,
        [MaterialAttribute(14539,1)]
        BrewingStand,
        [MaterialAttribute(26531,1)]
        Cauldron,
        [MaterialAttribute(24860,1)]
        EnderEye,
        [MaterialAttribute(20158,1)]
        GlisteringMelonSlice,
        [MaterialAttribute(14607,1)]
        BatSpawnEgg,
        [MaterialAttribute(22924,1)]
        BeeSpawnEgg,
        [MaterialAttribute(4759,1)]
        BlazeSpawnEgg,
        [MaterialAttribute(29583,1)]
        CatSpawnEgg,
        [MaterialAttribute(23341,1)]
        CaveSpiderSpawnEgg,
        [MaterialAttribute(5462,1)]
        ChickenSpawnEgg,
        [MaterialAttribute(27248,1)]
        CodSpawnEgg,
        [MaterialAttribute(14761,1)]
        CowSpawnEgg,
        [MaterialAttribute(9653,1)]
        CreeperSpawnEgg,
        [MaterialAttribute(20787,1)]
        DolphinSpawnEgg,
        [MaterialAttribute(14513,1)]
        DonkeySpawnEgg,
        [MaterialAttribute(19368,1)]
        DrownedSpawnEgg,
        [MaterialAttribute(11418,1)]
        ElderGuardianSpawnEgg,
        [MaterialAttribute(29488,1)]
        EndermanSpawnEgg,
        [MaterialAttribute(16617,1)]
        EndermiteSpawnEgg,
        [MaterialAttribute(21271,1)]
        EvokerSpawnEgg,
        [MaterialAttribute(22376,1)]
        FoxSpawnEgg,
        [MaterialAttribute(9970,1)]
        GhastSpawnEgg,
        [MaterialAttribute(20113,1)]
        GuardianSpawnEgg,
        [MaterialAttribute(14088,1)]
        HoglinSpawnEgg,
        [MaterialAttribute(25981,1)]
        HorseSpawnEgg,
        [MaterialAttribute(20178,1)]
        HuskSpawnEgg,
        [MaterialAttribute(23640,1)]
        LlamaSpawnEgg,
        [MaterialAttribute(26638,1)]
        MagmaCubeSpawnEgg,
        [MaterialAttribute(22125,1)]
        MooshroomSpawnEgg,
        [MaterialAttribute(11229,1)]
        MuleSpawnEgg,
        [MaterialAttribute(30080,1)]
        OcelotSpawnEgg,
        [MaterialAttribute(23759,1)]
        PandaSpawnEgg,
        [MaterialAttribute(23614,1)]
        ParrotSpawnEgg,
        [MaterialAttribute(24648,1)]
        PhantomSpawnEgg,
        [MaterialAttribute(22584,1)]
        PigSpawnEgg,
        [MaterialAttribute(16193,1)]
        PiglinSpawnEgg,
        [MaterialAttribute(30230,1)]
        PiglinBruteSpawnEgg,
        [MaterialAttribute(28659,1)]
        PillagerSpawnEgg,
        [MaterialAttribute(17015,1)]
        PolarBearSpawnEgg,
        [MaterialAttribute(24570,1)]
        PufferfishSpawnEgg,
        [MaterialAttribute(26496,1)]
        RabbitSpawnEgg,
        [MaterialAttribute(8726,1)]
        RavagerSpawnEgg,
        [MaterialAttribute(18739,1)]
        SalmonSpawnEgg,
        [MaterialAttribute(24488,1)]
        SheepSpawnEgg,
        [MaterialAttribute(31848,1)]
        ShulkerSpawnEgg,
        [MaterialAttribute(14537,1)]
        SilverfishSpawnEgg,
        [MaterialAttribute(15261,1)]
        SkeletonSpawnEgg,
        [MaterialAttribute(21356,1)]
        SkeletonHorseSpawnEgg,
        [MaterialAttribute(17196,1)]
        SlimeSpawnEgg,
        [MaterialAttribute(14984,1)]
        SpiderSpawnEgg,
        [MaterialAttribute(10682,1)]
        SquidSpawnEgg,
        [MaterialAttribute(30153,1)]
        StraySpawnEgg,
        [MaterialAttribute(6203,1)]
        StriderSpawnEgg,
        [MaterialAttribute(8439,1)]
        TraderLlamaSpawnEgg,
        [MaterialAttribute(19713,1)]
        TropicalFishSpawnEgg,
        [MaterialAttribute(17324,1)]
        TurtleSpawnEgg,
        [MaterialAttribute(27751,1)]
        VexSpawnEgg,
        [MaterialAttribute(30348,1)]
        VillagerSpawnEgg,
        [MaterialAttribute(25324,1)]
        VindicatorSpawnEgg,
        [MaterialAttribute(17904,1)]
        WanderingTraderSpawnEgg,
        [MaterialAttribute(11837,1)]
        WitchSpawnEgg,
        [MaterialAttribute(10073,1)]
        WitherSkeletonSpawnEgg,
        [MaterialAttribute(21692,1)]
        WolfSpawnEgg,
        [MaterialAttribute(7442,1)]
        ZoglinSpawnEgg,
        [MaterialAttribute(5814,1)]
        ZombieSpawnEgg,
        [MaterialAttribute(4275,1)]
        ZombieHorseSpawnEgg,
        [MaterialAttribute(10311,1)]
        ZombieVillagerSpawnEgg,
        [MaterialAttribute(6626,1)]
        ZombifiedPiglinSpawnEgg,
        [MaterialAttribute(12858,1)]
        ExperienceBottle,
        [MaterialAttribute(4842,1)]
        FireCharge,
        [MaterialAttribute(13393,1)]
        WritableBook,
        [MaterialAttribute(24164,1)]
        WrittenBook,
        [MaterialAttribute(5654,1)]
        Emerald,
        [MaterialAttribute(27318,1)]
        ItemFrame,
        [MaterialAttribute(30567,1)]
        FlowerPot,
        [MaterialAttribute(22824,1)]
        Carrot,
        [MaterialAttribute(21088,1)]
        Potato,
        [MaterialAttribute(14624,1)]
        BakedPotato,
        [MaterialAttribute(32640,1)]
        PoisonousPotato,
        [MaterialAttribute(21655,1)]
        Map,
        [MaterialAttribute(5300,1)]
        GoldenCarrot,
        [MaterialAttribute(13270,1)]
        SkeletonSkull,
        [MaterialAttribute(31487,1)]
        WitherSkeletonSkull,
        [MaterialAttribute(21174,1)]
        PlayerHead,
        [MaterialAttribute(9304,1)]
        ZombieHead,
        [MaterialAttribute(29146,1)]
        CreeperHead,
        [MaterialAttribute(20084,1)]
        DragonHead,
        [MaterialAttribute(27809,1)]
        CarrotOnAStick,
        [MaterialAttribute(11706,1)]
        WarpedFungusOnAStick,
        [MaterialAttribute(12469,1)]
        NetherStar,
        [MaterialAttribute(28725,1)]
        PumpkinPie,
        [MaterialAttribute(23841,1)]
        FireworkRocket,
        [MaterialAttribute(12190,1)]
        FireworkStar,
        [MaterialAttribute(11741,1)]
        EnchantedBook,
        [MaterialAttribute(19996,1)]
        NetherBrick,
        [MaterialAttribute(23608,1)]
        Quartz,
        [MaterialAttribute(4277,1)]
        TntMinecart,
        [MaterialAttribute(19024,1)]
        HopperMinecart,
        [MaterialAttribute(10993,1)]
        PrismarineShard,
        [MaterialAttribute(31546,1)]
        PrismarineCrystals,
        [MaterialAttribute(23068,1)]
        Rabbit,
        [MaterialAttribute(4454,1)]
        CookedRabbit,
        [MaterialAttribute(10611,1)]
        RabbitStew,
        [MaterialAttribute(13864,1)]
        RabbitFoot,
        [MaterialAttribute(12467,1)]
        RabbitHide,
        [MaterialAttribute(12852,1)]
        ArmorStand,
        [MaterialAttribute(30108,1)]
        IronHorseArmor,
        [MaterialAttribute(7996,1)]
        GoldenHorseArmor,
        [MaterialAttribute(10321,1)]
        DiamondHorseArmor,
        [MaterialAttribute(30667,1)]
        LeatherHorseArmor,
        [MaterialAttribute(29539,1)]
        Lead,
        [MaterialAttribute(30731,1)]
        NameTag,
        [MaterialAttribute(7992,1)]
        CommandBlockMinecart,
        [MaterialAttribute(4792,1)]
        Mutton,
        [MaterialAttribute(31447,1)]
        CookedMutton,
        [MaterialAttribute(17562,1)]
        WhiteBanner,
        [MaterialAttribute(4839,1)]
        OrangeBanner,
        [MaterialAttribute(15591,1)]
        MagentaBanner,
        [MaterialAttribute(18060,1)]
        LightBlueBanner,
        [MaterialAttribute(30382,1)]
        YellowBanner,
        [MaterialAttribute(18887,1)]
        LimeBanner,
        [MaterialAttribute(19439,1)]
        PinkBanner,
        [MaterialAttribute(12053,1)]
        GrayBanner,
        [MaterialAttribute(11417,1)]
        LightGrayBanner,
        [MaterialAttribute(9839,1)]
        CyanBanner,
        [MaterialAttribute(29027,1)]
        PurpleBanner,
        [MaterialAttribute(18481,1)]
        BlueBanner,
        [MaterialAttribute(11481,1)]
        BrownBanner,
        [MaterialAttribute(10698,1)]
        GreenBanner,
        [MaterialAttribute(26961,1)]
        RedBanner,
        [MaterialAttribute(9365,1)]
        BlackBanner,
        [MaterialAttribute(19090,1)]
        EndCrystal,
        [MaterialAttribute(7652,1)]
        ChorusFruit,
        [MaterialAttribute(27844,1)]
        PoppedChorusFruit,
        [MaterialAttribute(23305,1)]
        Beetroot,
        [MaterialAttribute(21282,1)]
        BeetrootSeeds,
        [MaterialAttribute(16036,1)]
        BeetrootSoup,
        [MaterialAttribute(20154,1)]
        DragonBreath,
        [MaterialAttribute(30248,1)]
        SplashPotion,
        [MaterialAttribute(4568,1)]
        SpectralArrow,
        [MaterialAttribute(25164,1)]
        TippedArrow,
        [MaterialAttribute(25857,1)]
        LingeringPotion,
        [MaterialAttribute(29943,1)]
        Shield,
        [MaterialAttribute(23829,1)]
        Elytra,
        [MaterialAttribute(9606,1)]
        SpruceBoat,
        [MaterialAttribute(28104,1)]
        BirchBoat,
        [MaterialAttribute(4495,1)]
        JungleBoat,
        [MaterialAttribute(27326,1)]
        AcaciaBoat,
        [MaterialAttribute(28618,1)]
        DarkOakBoat,
        [MaterialAttribute(10139,1)]
        TotemOfUndying,
        [MaterialAttribute(27848,1)]
        ShulkerShell,
        [MaterialAttribute(13715,1)]
        IronNugget,
        [MaterialAttribute(12646,1)]
        KnowledgeBook,
        [MaterialAttribute(24562,1)]
        DebugStick,
        [MaterialAttribute(16359,1)]
        MusicDisc13,
        [MaterialAttribute(16246,1)]
        MusicDiscCat,
        [MaterialAttribute(26667,1)]
        MusicDiscBlocks,
        [MaterialAttribute(19436,1)]
        MusicDiscChirp,
        [MaterialAttribute(13823,1)]
        MusicDiscFar,
        [MaterialAttribute(11517,1)]
        MusicDiscMall,
        [MaterialAttribute(26117,1)]
        MusicDiscMellohi,
        [MaterialAttribute(14989,1)]
        MusicDiscStal,
        [MaterialAttribute(16785,1)]
        MusicDiscStrad,
        [MaterialAttribute(24026,1)]
        MusicDiscWard,
        [MaterialAttribute(27426,1)]
        MusicDisc11,
        [MaterialAttribute(26499,1)]
        MusicDiscWait,
        [MaterialAttribute(21323,1)]
        MusicDiscPigstep,
        [MaterialAttribute(7534,1)]
        Trident,
        [MaterialAttribute(18398,1)]
        PhantomMembrane,
        [MaterialAttribute(19989,1)]
        NautilusShell,
        [MaterialAttribute(11807,1)]
        HeartOfTheSea,
        [MaterialAttribute(4340,1)]
        Crossbow,
        [MaterialAttribute(8173,1)]
        SuspiciousStew,
        [MaterialAttribute(14276,1)]
        Loom,
        [MaterialAttribute(5762,1)]
        FlowerBannerPattern,
        [MaterialAttribute(15774,1)]
        CreeperBannerPattern,
        [MaterialAttribute(7680,1)]
        SkullBannerPattern,
        [MaterialAttribute(11903,1)]
        MojangBannerPattern,
        [MaterialAttribute(27753,1)]
        GlobeBannerPattern,
        [MaterialAttribute(22028,1)]
        PiglinBannerPattern,
        [MaterialAttribute(31247,1)]
        Composter,
        [MaterialAttribute(22396,1)]
        Barrel,
        [MaterialAttribute(24781,1)]
        Smoker,
        [MaterialAttribute(31157,1)]
        BlastFurnace,
        [MaterialAttribute(28529,1)]
        CartographyTable,
        [MaterialAttribute(30838,1)]
        FletchingTable,
        [MaterialAttribute(26260,1)]
        Grindstone,
        [MaterialAttribute(23490,1)]
        Lectern,
        [MaterialAttribute(9082,1)]
        SmithingTable,
        [MaterialAttribute(25170,1)]
        Stonecutter,
        [MaterialAttribute(20000,1)]
        Bell,
        [MaterialAttribute(5992,1)]
        Lantern,
        [MaterialAttribute(27778,1)]
        SoulLantern,
        [MaterialAttribute(19747,1)]
        SweetBerries,
        [MaterialAttribute(8488,1)]
        Campfire,
        [MaterialAttribute(4238,1)]
        SoulCampfire,
        [MaterialAttribute(20424,1)]
        Shroomlight,
        [MaterialAttribute(9482,1)]
        Honeycomb,
        [MaterialAttribute(8825,1)]
        BeeNest,
        [MaterialAttribute(11830,1)]
        Beehive,
        [MaterialAttribute(22927,1)]
        HoneyBottle,
        [MaterialAttribute(30615,1)]
        HoneyBlock,
        [MaterialAttribute(28780,1)]
        HoneycombBlock,
        [MaterialAttribute(23127,1)]
        Lodestone,
        [MaterialAttribute(6527,1)]
        NetheriteBlock,
        [MaterialAttribute(18198,1)]
        AncientDebris,
        [MaterialAttribute(22637,1)]
        Target,
        [MaterialAttribute(31545,1)]
        CryingObsidian,
        [MaterialAttribute(7354,1)]
        Blackstone,
        [MaterialAttribute(11948,1)]
        BlackstoneSlab,
        [MaterialAttribute(14646,1)]
        BlackstoneStairs,
        [MaterialAttribute(8498,1)]
        GildedBlackstone,
        [MaterialAttribute(18144,1)]
        PolishedBlackstone,
        [MaterialAttribute(23430,1)]
        PolishedBlackstoneSlab,
        [MaterialAttribute(8653,1)]
        PolishedBlackstoneStairs,
        [MaterialAttribute(21942,1)]
        ChiseledPolishedBlackstone,
        [MaterialAttribute(19844,1)]
        PolishedBlackstoneBricks,
        [MaterialAttribute(12219,1)]
        PolishedBlackstoneBrickSlab,
        [MaterialAttribute(17983,1)]
        PolishedBlackstoneBrickStairs,
        [MaterialAttribute(16846,1)]
        CrackedPolishedBlackstoneBricks,
        [MaterialAttribute(4099,1)]
        RespawnAnchor,
        [MaterialAttribute(24998,1)]
        Water,
        [MaterialAttribute(8415,1)]
        Lava,
        [MaterialAttribute(27189,1)]
        TallSeagrass,
        [MaterialAttribute(30226,1)]
        PistonHead,
        [MaterialAttribute(13831,1)]
        MovingPiston,
        [MaterialAttribute(25890,1)]
        WallTorch,
        [MaterialAttribute(16396,1)]
        Fire,
        [MaterialAttribute(30163,1)]
        SoulFire,
        [MaterialAttribute(25984,1)]
        RedstoneWire,
        [MaterialAttribute(12984,1)]
        OakWallSign,
        [MaterialAttribute(7352,1)]
        SpruceWallSign,
        [MaterialAttribute(9887,1)]
        BirchWallSign,
        [MaterialAttribute(20316,1)]
        AcaciaWallSign,
        [MaterialAttribute(29629,1)]
        JungleWallSign,
        [MaterialAttribute(9508,1)]
        DarkOakWallSign,
        [MaterialAttribute(7595,1)]
        RedstoneWallTorch,
        [MaterialAttribute(27500,1)]
        SoulWallTorchs,
        [MaterialAttribute(19469,1)]
        NetherPortal,
        [MaterialAttribute(12724,1)]
        AttachedPumpkinStem,
        [MaterialAttribute(30882,1)]
        AttachedMelonStem,
        [MaterialAttribute(19021,1)]
        PumpkinStem,
        [MaterialAttribute(8247,1)]
        MelonStem,
        [MaterialAttribute(16782,1)]
        EndPortal,
        [MaterialAttribute(29709,1)]
        Cocoa,
        [MaterialAttribute(8810,1)]
        Tripwire,
        [MaterialAttribute(11905,1)]
        PottedOakSapling,
        [MaterialAttribute(29498,1)]
        PottedSpruceSapling,
        [MaterialAttribute(32484,1)]
        PottedBirchSapling,
        [MaterialAttribute(7525,1)]
        PottedJungleSapling,
        [MaterialAttribute(14096,1)]
        PottedAcaciaSapling,
        [MaterialAttribute(6486,1)]
        PottedDarkOakSapling,
        [MaterialAttribute(23315,1)]
        PottedFern,
        [MaterialAttribute(9727,1)]
        PottedDandelion,
        [MaterialAttribute(7457,1)]
        PottedPoppy,
        [MaterialAttribute(6599,1)]
        PottedBlueOrchid,
        [MaterialAttribute(13184,1)]
        PottedAllium,
        [MaterialAttribute(8754,1)]
        PottedAzureBluet,
        [MaterialAttribute(28594,1)]
        PottedRedTulip,
        [MaterialAttribute(28807,1)]
        PottedOrangeTulip,
        [MaterialAttribute(24330,1)]
        PottedWhiteTulip,
        [MaterialAttribute(10089,1)]
        PottedPinkTulip,
        [MaterialAttribute(19707,1)]
        PottedOxeyeDaisy,
        [MaterialAttribute(28917,1)]
        PottedCornflower,
        [MaterialAttribute(9364,1)]
        PottedLilyOfTheValley,
        [MaterialAttribute(26876,1)]
        PottedWitherRose,
        [MaterialAttribute(22881,1)]
        PottedRedMushroom,
        [MaterialAttribute(14481,1)]
        PottedBrownMushroom,
        [MaterialAttribute(13020,1)]
        PottedDeadBush,
        [MaterialAttribute(8777,1)]
        PottedCactus,
        [MaterialAttribute(17258,1)]
        Carrots,
        [MaterialAttribute(10879,1)]
        Potatoes,
        [MaterialAttribute(31650,1)]
        SkeletonWallSkull,
        [MaterialAttribute(9326,1)]
        WitherSkeletonWallSkull,
        [MaterialAttribute(16296,1)]
        ZombieWallHead,
        [MaterialAttribute(13164,1)]
        PlayerWallHead,
        [MaterialAttribute(30123,1)]
        CreeperWallHead,
        [MaterialAttribute(19818,1)]
        DragonWallHead,
        [MaterialAttribute(15967,1)]
        WhiteWallBanner,
        [MaterialAttribute(9936,1)]
        OrangeWallBanner,
        [MaterialAttribute(23291,1)]
        MagentaWallBanner,
        [MaterialAttribute(12011,1)]
        LightBlueWallBanner,
        [MaterialAttribute(32004,1)]
        YellowWallBanner,
        [MaterialAttribute(21422,1)]
        LimeWallBanner,
        [MaterialAttribute(9421,1)]
        PinkWallBanner,
        [MaterialAttribute(24275,1)]
        GrayWallBanner,
        [MaterialAttribute(31088,1)]
        LightGrayWallBanner,
        [MaterialAttribute(10889,1)]
        CyanWallBanner,
        [MaterialAttribute(14298,1)]
        PurpleWallBanner,
        [MaterialAttribute(17757,1)]
        BlueWallBanner,
        [MaterialAttribute(14731,1)]
        BrownWallBanner,
        [MaterialAttribute(15046,1)]
        GreenWallBanner,
        [MaterialAttribute(4378,1)]
        RedWallBanner,
        [MaterialAttribute(4919,1)]
        BlackWallBanner,
        [MaterialAttribute(22075,1)]
        Beetroots,
        [MaterialAttribute(26605,1)]
        EndGateway,
        [MaterialAttribute(21814,1)]
        FrostedIce,
        [MaterialAttribute(29697,1)]
        KelpPlant,
        [MaterialAttribute(5128,1)]
        DeadTubeCoralWallFan,
        [MaterialAttribute(23718,1)]
        DeadBrainCoralWallFan,
        [MaterialAttribute(18453,1)]
        DeadBubbleCoralWallFan,
        [MaterialAttribute(23375,1)]
        DeadFireCoralWallFan,
        [MaterialAttribute(27550,1)]
        DeadHornCoralWallFan,
        [MaterialAttribute(25282,1)]
        TubeCoralWallFan,
        [MaterialAttribute(22685,1)]
        BrainCoralWallFan,
        [MaterialAttribute(20382,1)]
        BubbleCoralWallFan,
        [MaterialAttribute(20100,1)]
        FireCoralWallFan,
        [MaterialAttribute(28883,1)]
        HornCoralWallFan,
        [MaterialAttribute(8478,1)]
        BambooSapling,
        [MaterialAttribute(22542,1)]
        PottedBamboo,
        [MaterialAttribute(13668,1)]
        VoidAir,
        [MaterialAttribute(17422,1)]
        CaveAir,
        [MaterialAttribute(31612,1)]
        BubbleColumn,
        [MaterialAttribute(11958,1)]
        SweetBerryBush,
        [MaterialAttribute(19437,1)]
        WeepingVinesPlant,
        [MaterialAttribute(25338,1)]
        TwistingVinesPlant,
        [MaterialAttribute(19242,1)]
        CrimsonWallSign,
        [MaterialAttribute(13534,1)]
        WarpedWallSign,
        [MaterialAttribute(5548,1)]
        PottedCrimsonFungus,
        [MaterialAttribute(30800,1)]
        PottedWarpedFungus,
        [MaterialAttribute(13852,1)]
        PottedCrimsonRoots,
        [MaterialAttribute(6403,1)]
        PottedWarpedRoots,
        
        
        [MaterialAttribute(9)]
        StationaryWater,
        [MaterialAttribute(11)]
        StationaryLava,
    }

    internal class MaterialAttribute : System.Attribute
    {
        public readonly int Id;
        public readonly int OldId;
        
        public readonly int MaxStack;
        public readonly short Durability;

        public readonly byte SubId;

        public MaterialAttribute(int id, int oldId, byte subId, int stack, short durability)
        {
            Id = id;
            OldId = oldId;
            SubId = subId;
            MaxStack = stack;
            Durability = durability;
        }
        public MaterialAttribute(int id, int oldId, byte subId, int stack) : this(id, oldId, subId, stack, 0) {}
        public MaterialAttribute(int id, int oldId, byte subId) : this(id, oldId, subId, 64, 0) {}
        public MaterialAttribute(int id, int oldId) : this(id, oldId, 0, 64, 0) {}

        public MaterialAttribute(int id) : this(id, id, 0, 64, 0) {}
    }

    public static class MaterialExtensions
    {
        public static int GetId(this Material m)
        {
            MaterialAttribute[] attributes =
                (MaterialAttribute[]) m.GetType().GetField(m.ToString())!.GetCustomAttributes(typeof(MaterialAttribute), false);
            if (attributes.Length > 0)
                return attributes[0].Id;

            return -1;
        }
        
        public static int GetOldId(this Material m)
        {
            MaterialAttribute[] attributes =
                (MaterialAttribute[]) m.GetType().GetField(m.ToString())!.GetCustomAttributes(typeof(MaterialAttribute),
                    false);
            if (attributes.Length > 0)
                return attributes[0].OldId;

            return -1;
        }
        
        public static int GetOldSubId(this Material m)
        {
            MaterialAttribute[] attributes =
                (MaterialAttribute[]) m.GetType().GetField(m.ToString())!.GetCustomAttributes(typeof(MaterialAttribute),
                    false);
            if (attributes.Length > 0)
                return attributes[0].SubId;

            return -1;
        }
        
        public static int GetMaxStack(this Material m)
        {
            MaterialAttribute[] attributes =
                (MaterialAttribute[]) m.GetType().GetField(m.ToString())!.GetCustomAttributes(typeof(MaterialAttribute),
                    false);
            if (attributes.Length > 0)
                return attributes[0].MaxStack;

            return -1;
        }
        
        public static int GetDurability(this Material m)
        {
            MaterialAttribute[] attributes =
                (MaterialAttribute[]) m.GetType().GetField(m.ToString())!.GetCustomAttributes(typeof(MaterialAttribute),
                    false);
            if (attributes.Length > 0)
                return attributes[0].Durability;

            return -1;
        }

        public static bool IsBlock(this Material m)
        {
            switch (m)
            {
            }

            return false;
        }
    }
}